databases:
  - name: spam_sleuth
    databaseName: spam_sleuth_b1qg
    user: spam_sleuth_b1qg_user


services:
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: free
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: postgres://spam_sleuth_b1qg_user:KnJ5vC3Rnrt3e6WWsAMWQszCDRDElcGd@dpg-ciihgb6nqql0tc45uo0g-a/spam_sleuth_b1qg
        fromDatabase:
          name: spam_sleuth
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
