databases:
  - name: spam_sleuth
    databaseName: spam_sleuth_b1qg
    user: spam_sleuth_b1qg_user
    password: KnJ5vC3Rnrt3e6WWsAMWQszCDRDElcGd
    host: dpg-ciihgb6nqql0tc45uo0g-a
    port: 5432


services:
  - type: pserv
    name: pgbouncer
    runtime: docker
    plan: standard
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
